// Include Standard files
#include "include/AT91SAM7X-EK.h"
#include <pit/pit.h>
#include <aic/aic.h>

/* Global variables */
#define SPEED 		(MCKKHz/1000)
/// PIT period value in µseconds.
#define PIT_PERIOD          250000

unsigned int LedSpeed = SPEED *5000 ;
const int ledmask[NB_LED]= {LED1, LED2, LED3, LED4};
char tick1;
void ConfigSyst(void);

void wait ( void )
{
    unsigned int waiting_time ;
    for(waiting_time = 0; waiting_time < LedSpeed; waiting_time++) ;
}

void ISR_PIT (void)
{
// This function is to be executed for each interrupt on PIT
    unsigned int dummy;
// Read the PIT status register
    dummy = AT91C_BASE_PITC->PITC_PISR & AT91C_PITC_PITS;
    if (dummy != 0) 
	{         
    		tick1++;
    		tick1&=1;
    		if (tick1==0)
    		{
           		BASE_PIO_LED->PIO_SODR = LED2;
		}
    		else
    		{
            	BASE_PIO_LED->PIO_CODR ^= LED2;
    		}
// Read the PIVR to acknowledge interrupt and end ISR
    	dummy=  AT91C_BASE_PITC->PITC_PIVR;
    	}
}

int main()
{ 
    ConfigSyst();
    tick1=0;
    BASE_PIO_LED->PIO_CODR = LED2;
    // infinite loop to make LED1 blink.
    for (;;)
    {
        BASE_PIO_LED->PIO_SODR = LED1;
        wait();
        BASE_PIO_LED->PIO_CODR = LED1;
        wait();
    }   
}



void ConfigSyst(void){
// First, activate PIO_LED
       	AT91C_BASE_PMC->PMC_PCER =  (1 << ID_PIO_LED);
//then set IOs
	BASE_PIO_LED->PIO_PER = LED_MASK; // Set in PIO mode
	BASE_PIO_LED->PIO_OER = LED_MASK; // Configure in Output
// and switch off all LEDs
	BASE_PIO_LED->PIO_SODR = LED_MASK ;
           
/*Peripheral Interval Timer (PIT): generate periodic interrupts. 
it provides the base tick of an operating system. The PIT uses MCK /16 as its input clock, as well as a 20-bit counter. Each time the counter reaches a programmable value, an interrupt is generated, and a second counter increments. The latter makes it possible to never miss a tick, even when the system is overloaded.*/

// PIT initialization
// To be completed, expected PIT period is 0.25s

/* Since the PIT is part of the System Controller, it is continuously clocked. As such, there is no need to enable its peripheral clock in the PMC.
The Mode Register contains the Periodic Interval Value (PIV) which indicates to the PIT when to reset the internal counter. It must be programmed to the number of ticks generated by MCK/16 */
	
// This is done with the following line of code:(250 ms tick)

 AT91C_BASE_PITC->PITC_PIMR = BOARD_MCK/100000 * PIT_PERIOD +8;

// Before starting the timer, the interrupt must be configured in the AIC. Please refer to Section AIC initialization_ advanced interrupt controller
           
// Disable all interrupts
	AT91C_BASE_AIC->AIC_IDCR = 0xFFFFFFFF;
// Clear all interrupts
	AT91C_BASE_AIC->AIC_ICCR = 0xFFFFFFFF;
  
// Configure interrupt on PIT
    	AT91C_BASE_AIC->AIC_SMR[AT91C_ID_SYS] |= AT91C_AIC_SRCTYPE_INT_HIGH_LEVEL; 
// Mode haut niveau (détection d'interruption)
    	AT91C_BASE_AIC->AIC_SVR[AT91C_ID_SYS] = (unsigned) ISR_PIT; 

    	AT91C_BASE_AIC->AIC_IECR = 1 << AT91C_ID_SYS;
    	AT91C_BASE_PITC->PITC_PIMR |= AT91C_PITC_PITIEN;

// Enable the pit
    	AT91C_BASE_PITC->PITC_PIMR |= AT91C_PITC_PITEN;
}